# Generated by Django 5.2.10 on 2026-01-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_category', models.CharField(max_length=100)),
                ('date_and_time', models.DateTimeField()),
                ('venue', models.CharField()),
                ('organizer', models.CharField()),
                ('registration_link', models.CharField()),
            ],
        ),
    ]
